.TH CONNSCAN 1 "July 2025" "Version 1.0" "User Commands"
.SH NAME
CONNSCAN \- lists connected ip-addresses
.SH SYNOPSIS
.B connscan
[\fIOPTIONS\fR]
.SH DESCRIPTION
This program will list hosts:services connected to your device
Currently no options, is used with showhosts - yes not optimal.
.TP
quick way to see who is connected to your host on what ports
.SH OPTIONS
.TP
.B default
Show IP's and ports
.TP

.SH AUTHOR
mip.

.SH SEE ALSO
go(1)

